// packages/react-virtual/lib/table/table.tsx
import React, {
  createContext,
  ReactNode,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";

export interface TableContextValue {
  totalData: number;
  rowHeight?: number;
  height?: number;
  scrollTop: number;
  contentWidth: number;
  columnWidths: number[];
  overscan: number;
  startIndex: number;
  endIndex: number;
  setColumnWidths: (widths: number[]) => void; // Function to update column widths from Thead
  columnCount: number; // Number of columns (for border calculations)
}

const TableContext = createContext<TableContextValue | null>(null);

export const useTableContext = (): TableContextValue => {
  const context = useContext(TableContext);
  if (!context) {
    throw new Error("Table components must be used within a Table provider");
  }
  return context as TableContextValue;
};

export interface TableProps {
  totalData: number;
  rowHeight?: number;
  height?: number;
  containerStyle?: Omit<
    React.CSSProperties,
    "width" | "height" | "position" | "overflow"
  >;
  overscan?: number;
  children: ReactNode;
  containerClassName?: string;
}

const Table = ({
  totalData,
  rowHeight = 40,
  children,
  height = 200,
  overscan = 5,
  containerStyle,
  containerClassName,
}: TableProps) => {
  const scrollElementRef = useRef<HTMLDivElement>(null);
  const [scrollTop, setScrollTop] = useState(0);
  const [columnWidths, setColumnWidths] = useState<number[]>([]);

  const handleScroll = useCallback((e: React.UIEvent<HTMLDivElement>) => {
    setScrollTop(e.currentTarget.scrollTop);
  }, []);

  // Stable setter function to prevent unnecessary re-renders
  const stableSetColumnWidths = useCallback((widths: number[]) => {
    setColumnWidths((prev) => {
      // Only update if widths actually changed
      if (
        prev.length !== widths.length ||
        prev.some((w, i) => w !== widths[i])
      ) {
        return widths;
      }
      return prev;
    });
  }, []);

  // Calculate total content width (sum of all column widths)
  const contentWidth = useMemo(() => {
    return columnWidths.reduce((sum, w) => sum + w, 0);
  }, [columnWidths]);

  const { startIndex, endIndex } = useMemo(() => {
    const visibleStart = Math.floor(scrollTop / rowHeight);
    const visibleEnd = Math.ceil((scrollTop + height) / rowHeight);
    const startIndex = Math.max(0, visibleStart - overscan);
    const endIndex = Math.min(totalData, visibleEnd + overscan);

    return { startIndex, endIndex };
  }, [scrollTop, height, rowHeight, totalData, overscan]);

  // Update container width based on content width comparison
  useEffect(() => {
    const updateWidth = () => {
      if (scrollElementRef.current && contentWidth > 0) {
        // Get the container's current width (which is 100% initially)
        // We need to get the parent's width or the actual rendered width
        const container = scrollElementRef.current;
        // Temporarily ensure width is 100% to get accurate measurement
        container.style.width = "100%";
        // Use requestAnimationFrame to ensure layout has updated
        requestAnimationFrame(() => {
          if (scrollElementRef.current) {
            const containerWidth = scrollElementRef.current.clientWidth;
            if (contentWidth > containerWidth) {
              scrollElementRef.current.style.width = "100%";
            } else {
              scrollElementRef.current.style.width = "fit-content";
            }
          }
        });
      }
    };

    updateWidth();

    // Handle window resize
    window.addEventListener("resize", updateWidth);
    return () => {
      window.removeEventListener("resize", updateWidth);
    };
  }, [contentWidth]);

  const contextValue: TableContextValue = {
    totalData,
    rowHeight,
    scrollTop,
    contentWidth,
    columnWidths,
    overscan,
    startIndex,
    endIndex,
    setColumnWidths: stableSetColumnWidths,
    columnCount: columnWidths.length,
  };

  return (
    <TableContext.Provider value={contextValue as TableContextValue}>
      <div
        style={{
          height,
          width: "100%",
          overflow: "auto",
          position: "relative",
          ...containerStyle,
          border: "1px solid",
          borderRadius: "4px",
        }}
        {...(containerClassName && { className: containerClassName })}
        ref={scrollElementRef}
        onScroll={handleScroll}
      >
        {children}
      </div>
    </TableContext.Provider>
  );
};

export default Table;

// packages/svelte-virtual/lib/table/table.svelte
<script lang="ts">
  import { setContext } from "svelte";
  import { tableContextKey } from "./context";

  // ✅ Get props reactively
  let {
    totalData,
    rowHeight = 40,
    height = 400,
    containerStyle = {},
    overscan = 5,
    containerClassName = "",
    children,
  } = $props();

  // ✅ Define internal state (for scroll, etc.)
  let scrollTop = $state(0);
  let columnWidths = $state([]);

  const visibleStart = $derived(Math.floor(scrollTop / rowHeight));
  const visibleEnd = $derived(Math.ceil((scrollTop + height) / rowHeight));
  const startIndex = $derived(Math.max(0, visibleStart - overscan));
  const endIndex = $derived(Math.min(totalData, visibleEnd + overscan));

  const contentWidth = $derived(columnWidths.reduce((sum, w) => sum + w, 0));

  const setColumnWidths = (newWidths: number[]) => {
    // Only update if widths actually changed
    if (
      columnWidths.length !== newWidths.length ||
      columnWidths.some((w, i) => w !== newWidths[i])
    ) {
      columnWidths = newWidths;
    }
  };

  // ✅ Provide all context values
  setContext(tableContextKey, {
    get totalData() {
      return totalData;
    },
    get rowHeight() {
      return rowHeight;
    },
    get height() {
      return height;
    },
    get overscan() {
      return overscan;
    },
    get scrollTop() {
      return scrollTop;
    },
    get contentWidth() {
      return contentWidth;
    },
    get columnWidths() {
      return columnWidths;
    },
    get startIndex() {
      return startIndex;
    },
    get endIndex() {
      return endIndex;
    },
    get columnCount() {
      return columnWidths.length;
    },
    setColumnWidths,
  });

  let scrollElementRef: HTMLDivElement | null = null;

  $effect(() => {
    const updateWidth = () => {
      if (scrollElementRef && contentWidth > 0) {
        // Get the container's current width (which is 100% initially)
        // We need to get the parent's width or the actual rendered width
        const container = scrollElementRef;
        // Temporarily ensure width is 100% to get accurate measurement
        container.style.width = "100%";
        // Use requestAnimationFrame to ensure layout has updated
        requestAnimationFrame(() => {
          if (scrollElementRef) {
            const containerWidth = scrollElementRef.clientWidth;
            if (contentWidth > containerWidth) {
              scrollElementRef.style.width = "100%";
            } else {
              scrollElementRef.style.width = "fit-content";
            }
          }
        });
      }
    };
    updateWidth();

    // Handle window resize
    window.addEventListener("resize", updateWidth);
    return () => {
      window.removeEventListener("resize", updateWidth);
    };
  });

  const handleScroll = (event: Event) => {
    scrollTop = (event.target as HTMLDivElement).scrollTop;
  };
</script>

<div
  bind:this={scrollElementRef}
  class={containerClassName}
  style={`height: ${height}px !important; position: relative !important; width: 100%; overflow: auto; border: 1px solid; border-radius: 4px !important; ${containerStyle}`}
  onscroll={handleScroll}
>
  {@render children()}
</div>
