// packages/react-virtual/lib/table/thead.tsx
import React, { createContext, useContext, useLayoutEffect } from "react";
import { useTableContext } from "./table";

interface TheadContextValue {
  columnCount: number;
  // Context exists to ensure Th is wrapped in Thead
  // The colIndex is injected via props by React.cloneElement
}

const TheadContext = createContext<TheadContextValue | null>(null);

export const useTheadContext = (): TheadContextValue => {
  const context = useContext(TheadContext);
  if (!context) {
    throw new Error("Th component must be used inside Thead component");
  }
  return context;
};

interface IProps extends React.HTMLAttributes<HTMLDivElement> {
  headerHeight?: number;
}

const Thead = ({ children, style, headerHeight = 50, ...props }: IProps) => {
  const { contentWidth, setColumnWidths, columnCount } = useTableContext();

  // Extract widths from Th children and update table context
  // The setColumnWidths function now handles change detection internally
  useLayoutEffect(() => {
    const widths: number[] = [];
    React.Children.forEach(children, (child) => {
      if (React.isValidElement(child)) {
        const thProps = child.props as { width?: number };
        widths.push(thProps.width ?? 100);
      }
    });
    if (widths.length > 0) {
      setColumnWidths(widths);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [children, setColumnWidths]);

  const contextValue: TheadContextValue = {
    columnCount,
  };

  return (
    <TheadContext.Provider value={contextValue}>
      <div
        style={{
          position: "sticky",
          top: 0,
          zIndex: 10,
          display: "flex",
          height: headerHeight,
          width: contentWidth,
          boxSizing: "border-box",
          ...style,
          backgroundColor: "#f5f5f5",
          borderBottom: "2px solid #ddd",
        }}
        {...props}
      >
        {React.Children.map(children, (child, index) => {
          if (React.isValidElement(child)) {
            return React.cloneElement(child, { colIndex: index } as any);
          }
          return child;
        })}
        {/* Spacer to fill remaining space when content is smaller than container */}
        {/* {needsFill && spacerWidth > 0 && (
          <div
            style={{
              width: spacerWidth,
              minWidth: spacerWidth,
              maxWidth: spacerWidth,
              flexShrink: 0,
              flexGrow: 0,
            }}
          />
        )} */}
      </div>
    </TheadContext.Provider>
  );
};

export default Thead;

// packages/svelte-virtual/lib/table/thead.svelte
<script lang="ts">
  import { getContext, setContext, tick } from "svelte";
  import { tableContextKey, theadContextKey } from "./context";

  const tableContext = getContext(tableContextKey);
  if (!tableContext) throw new Error("<Thead> must be used inside <Table>");

  let { children, headerHeight = 50, ...props } = $props();

  const { contentWidth, setColumnWidths, columnCount } = tableContext as any;

  let containerRef: HTMLDivElement | null = null;

  // Extract widths from Th children and update table context
  // Similar to React's useLayoutEffect
  $effect(() => {
    tick().then(() => {
      // Wait for DOM updates
      if (!containerRef) return;

      const widths: number[] = [];
      const thElements = containerRef.querySelectorAll("[data-th-element]");

      thElements.forEach((el, index) => {
        const width = Number(el.getAttribute("width")) || 100;
        widths.push(width);
        // Set colIndex on each child element (similar to React.cloneElement)
        el.setAttribute("data-col-index", String(index));
      });

      if (widths.length > 0) {
        setColumnWidths(widths);
      }
    });
  });

  // Provide TheadContext (similar to TheadContext.Provider in React)
  setContext(theadContextKey, {
    get columnCount() {
      return columnCount;
    },
  });
</script>

<div
  bind:this={containerRef}
  data-thead-container
  style="position: sticky; top: 0; z-index: 10; display: flex; height: {headerHeight}px; box-sizing: border-box; background-color: #f5f5f5; border-bottom: 2px solid #ddd;"
  {...props}
>
  {@render children()}
</div>
