// packages/react-virtual/lib/HelloWorld.tsx
import React from "react";

export interface HelloWorldProps {
  name?: string;
}

export const HelloWorld: React.FC<HelloWorldProps> = ({ name = "World" }) => {
  return (
    <div
      style={{
        padding: "20px",
        border: "2px solid #646cff",
        borderRadius: "8px",
        backgroundColor: "#f9f9f9",
        textAlign: "center",
        fontSize: "24px",
        color: "#213547",
      }}
    >
      Hello, {name}! 👋
    </div>
  );
};

// packages/svelte-virtual/lib/HelloWorld.svelte
<script lang="ts">
  export let name: string = "World";
</script>

<div class="hello-world">
  Hello, {name}! 👋
</div>

<style>
  .hello-world {
    padding: 20px;
    border: 2px solid #ff3e00;
    border-radius: 8px;
    background-color: #fff5f0;
    text-align: center;
    font-size: 24px;
    color: #213547;
  }
</style>
