// packages/svelte-virtual/lib/table/tbody.svelte
<script lang="ts">
  import { getContext, setContext, tick } from "svelte";
  import { tableContextKey, tbodyContextKey } from "./context";

  let { children, offsetHeight = 45, ...props } = $props();

  const tableContext = getContext(tableContextKey);
  if (!tableContext) throw new Error("<Tbody> must be used inside <Table>");

  const {
    rowHeight,
    totalData,
    startIndex,
    endIndex,
    contentWidth,
    columnWidths,
    columnCount,
  } = tableContext as any;

  const totalHeight = totalData * offsetHeight;

  let containerRef: HTMLDivElement | null = null;

  // Provide TbodyContext (similar to TbodyContext.Provider in React)
  setContext(tbodyContextKey, {
    get contentWidth() {
      return contentWidth;
    },
    get rowHeight() {
      return rowHeight;
    },
    get columnWidths() {
      return columnWidths;
    },
    get columnCount() {
      return columnCount;
    },
  });

  // Inject rowIndex on Tr elements (similar to React.cloneElement)
  $effect(() => {
    tick().then(() => {
      if (!containerRef) return;

      const trElements = containerRef.querySelectorAll("[data-tr-element]");
      trElements.forEach((el, index) => {
        // Inject rowIndex as absolute index (startIndex + relative index in children)
        el.setAttribute("data-row-index", String(startIndex + index));
      });
    });
  });
</script>

<div
  bind:this={containerRef}
  style="position: relative; height: {totalHeight}px; width: {contentWidth}px; box-sizing: border-box;"
  {...props}
>
  <!-- Spacer for rows before visible range -->
  <div style="height: {startIndex * rowHeight}px;" />

  <!-- Render visible rows (children are rendered here, but we need to inject rowIndex) -->
  {@render children()}

  <!-- Spacer for rows after visible range -->
  <div style="height: {(totalData - endIndex) * rowHeight}px;" />
</div>

// packages/react-virtual/lib/table/tbody.tsx
import React, { createContext, useContext } from "react";
import { useTableContext } from "./table";

interface TbodyContextValue {
  contentWidth: number;
  rowHeight: number;
  columnWidths: number[];
  columnCount: number;
  // Context exists to ensure Tr is wrapped in Tbody
  // The rowIndex is injected via props by React.cloneElement
}

const TbodyContext = createContext<TbodyContextValue | null>(null);

export const useTbodyContext = (): TbodyContextValue => {
  const context = useContext(TbodyContext);
  if (!context) {
    throw new Error("Tr component must be used inside Tbody component");
  }
  return context;
};

interface IProps extends React.HTMLAttributes<HTMLDivElement> {
  offsetHeight?: number;
}

const Tbody = ({ children, offsetHeight = 45, style, ...props }: IProps) => {
  const {
    rowHeight,
    totalData,
    startIndex,
    endIndex,
    contentWidth,
    columnWidths,
    columnCount,
  } = useTableContext();

  const totalHeight = totalData * offsetHeight;

  const contextValue: TbodyContextValue = {
    contentWidth,
    rowHeight,
    columnWidths,
    columnCount,
  };

  return (
    <TbodyContext value={contextValue}>
      <div
        style={{
          position: "relative",
          height: totalHeight,
          width: contentWidth,
          boxSizing: "border-box",
          ...style,
        }}
        {...props}
      >
        <div style={{ height: startIndex * rowHeight }} />

        {React.Children.map(children, (child, index) => {
          if (React.isValidElement(child)) {
            // Inject rowIndex as absolute index (startIndex + relative index in children)
            return React.cloneElement(child, {
              rowIndex: startIndex + index,
            } as any);
          }
          return child;
        }).slice(startIndex, endIndex)}

        <div style={{ height: (totalData - endIndex) * rowHeight }} />
      </div>
    </TbodyContext>
  );
};

export default Tbody;
